### ISSUE TITLE
Update colors to match exact colors

### ISSUE THREAD

**Issue by wuz** [DankNeon/atom#3]
There are a few colors that are a bit off. The hex and rgb codes can be found in this PR: https://github.com/DankNeon/meta/blob/db05005f6bdc458bf54c141629e5d27123ea41e0/README.md

We need to update the colors to match correctly.

**Comment by stephfh** [comment]
Ah, didn't see the meta repo there. 😆

Looks much better already. 
<img width="1552" alt="screenshot 2019-01-21 at 22 32 30" src="https://user-images.githubusercontent.com/4586850/51499939-7a115180-1dcc-11e9-8e7d-cc6fb891ec9f.png">

Maybe pinning the meta-repo in the organisation might be a good idea.

**Comment by wuz** [comment]
No worries! The colors are still in a WIP PR too!

> Maybe pinning the meta-repo in the organisation might be a good idea.

Great idea!
